site:
  title: Semantic Aspect Meta Model
  url: https://github.com/eclipse-esmf/esmf-semantic-aspect-meta-model/
  start_page: samm-specification::index.adoc
content:
  sources:
    - url: .
      branches: HEAD
      start_path: documentation
ui:
  bundle:
    url: https://github.com/eclipse-esmf/esmf-antora-ui/releases/download/v1.2.0/esmf-antora-ui-bundle-1.2.0.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files: [ .nojekyll ]
    - path: .nojekyll
runtime:
  cache_dir: ./.cache/antora
asciidoc:
  attributes:
    # attribute-missing configures the asciidoc processor to warn on unresolved
    # references, see https://docs.asciidoctor.org/asciidoc/latest/attributes/unresolved-references/#missing
    # 'warn' is the default value, but by setting it to 'warn@' we allow pages
    # to override this setting. This is necessary to silence false positive
    # warnings that appear on inclusion of certain RDF source codes.
    attribute-missing: warn@
    doctype: book
    sectanchors: true
    idprefix: ''
    idseparator: '-'
    stem: 'asciimath'
    ok: 'icon:check-circle[role="green",size="2x"]'
    nok: 'icon:times-circle[role="red",size="2x"]'
    meta-model-version: 2.1.0
    meta-model-full-name: Semantic Aspect Meta Model
    meta-model-abbr: SAMM
    samm: urn:samm:org.eclipse.esmf.samm:meta-model:2.1.0#@
    samm-c: urn:samm:org.eclipse.esmf.samm:characteristic:2.1.0#@
    samm-e: urn:samm:org.eclipse.esmf.samm:entity:2.1.0#@
    unit: urn:samm:org.eclipse.esmf.samm:unit:2.1.0#@
    example-ns: com.mycompany@

